{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voidcache.fullname" . }}-secret
  namespace: {{ include "voidcache.namespace" . }}
  labels:
    {{- include "voidcache.labels" . | nindent 4 }}
type: Opaque
stringData:
  VC_PASSWORD: {{ .Values.auth.password | quote }}
{{- end }}
